# Generated by Django 5.1.1 on 2024-10-26 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Oziq-ovqat nomi')),
                ('tarkibi', models.TextField(verbose_name='Tarkibi')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('korishlar_soni', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='food_images/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Oziq-ovqat',
                'verbose_name_plural': 'Oziq-ovqatlar',
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Tur nomi')),
            ],
            options={
                'verbose_name': 'Oziq-ovqat turi',
                'verbose_name_plural': 'Oziq-ovqat turlari',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Komment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fastfood_app.food')),
            ],
            options={
                'verbose_name': 'Komment',
                'verbose_name_plural': 'Kommentlar',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood_app.foodtype', verbose_name='Oziq-ovqat turi'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='fastfood_app.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('food', 'user')},
            },
        ),
    ]
